
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1333, 830)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -30, 1341, 951))
        self.label.setMinimumSize(QtCore.QSize(1341, 951))
        self.label.setMaximumSize(QtCore.QSize(1340, 951))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Emirhan/Desktop/arkaplan.webp"))
        self.label.setObjectName("label")
        self.baslik = QtWidgets.QLabel(self.centralwidget)
        self.baslik.setGeometry(QtCore.QRect(510, 40, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.baslik.setFont(font)
        self.baslik.setMouseTracking(False)
        self.baslik.setStyleSheet("color: rgb(255, 255, 255);")
        self.baslik.setAlignment(QtCore.Qt.AlignCenter)
        self.baslik.setObjectName("baslik")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 180, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 230, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 290, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 350, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.ad = QtWidgets.QLineEdit(self.centralwidget)
        self.ad.setGeometry(QtCore.QRect(210, 190, 151, 31))
        self.ad.setObjectName("ad")
        self.soyad = QtWidgets.QLineEdit(self.centralwidget)
        self.soyad.setGeometry(QtCore.QRect(210, 240, 151, 31))
        self.soyad.setObjectName("soyad")
        self.tc = QtWidgets.QLineEdit(self.centralwidget)
        self.tc.setGeometry(QtCore.QRect(210, 300, 151, 31))
        self.tc.setObjectName("tc")
        self.telefon = QtWidgets.QLineEdit(self.centralwidget)
        self.telefon.setGeometry(QtCore.QRect(210, 360, 151, 31))
        self.telefon.setObjectName("telefon")
        self.cinsiyet = QtWidgets.QGroupBox(self.centralwidget)
        self.cinsiyet.setGeometry(QtCore.QRect(960, 280, 231, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.cinsiyet.setFont(font)
        self.cinsiyet.setStyleSheet("color: rgb(255, 255, 255);")
        self.cinsiyet.setAlignment(QtCore.Qt.AlignCenter)
        self.cinsiyet.setObjectName("cinsiyet")
        self.erkek = QtWidgets.QRadioButton(self.cinsiyet)
        self.erkek.setGeometry(QtCore.QRect(20, 30, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.erkek.setFont(font)
        self.erkek.setObjectName("erkek")
        self.kadin = QtWidgets.QRadioButton(self.cinsiyet)
        self.kadin.setGeometry(QtCore.QRect(130, 30, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kadin.setFont(font)
        self.kadin.setObjectName("kadin")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(830, 180, 231, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: rgb(0, 0, 0);")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.dogumyer = QtWidgets.QComboBox(self.groupBox)
        self.dogumyer.setGeometry(QtCore.QRect(20, 40, 191, 31))
        self.dogumyer.setObjectName("dogumyer")
        self.dogumyer.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(1070, 180, 231, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.bolum = QtWidgets.QComboBox(self.groupBox_2)
        self.bolum.setGeometry(QtCore.QRect(20, 40, 191, 31))
        self.bolum.setObjectName("bolum")
        self.bolum.addItem("")
        self.bolum.addItem("")
        self.bolum.addItem("")
        self.bolum.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(560, 130, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.dogumyili = QtWidgets.QCalendarWidget(self.centralwidget)
        self.dogumyili.setGeometry(QtCore.QRect(440, 180, 376, 218))
        self.dogumyili.setObjectName("dogumyili")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(430, 430, 451, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.kayitekle = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.kayitekle.setFont(font)
        self.kayitekle.setObjectName("kayitekle")
        self.horizontalLayout.addWidget(self.kayitekle)
        self.kayitsil = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.kayitsil.setFont(font)
        self.kayitsil.setObjectName("kayitsil")
        self.horizontalLayout.addWidget(self.kayitsil)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 530, 1341, 401))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(157)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(66)
        self.tableWidget.verticalHeader().setDefaultSectionSize(35)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Öğrenci Kayıt Sistemi"))
        self.baslik.setText(_translate("MainWindow", "Öğrenci Kayıt Sistemi"))
        self.label_2.setText(_translate("MainWindow", "Ad :"))
        self.label_3.setText(_translate("MainWindow", "Soyad :"))
        self.label_4.setText(_translate("MainWindow", "Tc No :"))
        self.label_5.setText(_translate("MainWindow", "Telefon :"))
        self.cinsiyet.setTitle(_translate("MainWindow", "Cinsiyet"))
        self.erkek.setText(_translate("MainWindow", "Erkek"))
        self.kadin.setText(_translate("MainWindow", "Kadın"))
        self.groupBox.setTitle(_translate("MainWindow", "Doğum Yeri"))
        self.dogumyer.setItemText(0, _translate("MainWindow", "Adana"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Bölüm"))
        self.bolum.setItemText(0, _translate("MainWindow", "Sayısal"))
        self.bolum.setItemText(1, _translate("MainWindow", "Eşit Ağırlık"))
        self.bolum.setItemText(2, _translate("MainWindow", "Sözel"))
        self.bolum.setItemText(3, _translate("MainWindow", "Dil"))
        self.label_6.setText(_translate("MainWindow", "Doğum Tarihi"))
        self.kayitekle.setText(_translate("MainWindow", "Kayıt Ekle"))
        self.kayitsil.setText(_translate("MainWindow", "Kayıt Sil"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Adı"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Soyadı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tc No"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Telefon"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Doğum Tarihi"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Doğum Yeri"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Bölümü"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Cinsiyeti"))
